server:
  port: 8087

spring:
  profiles: dev
  application:
    name: config-server-dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource